Feature: Sharing of the database
SecUSo/privacy-friendly-food-tracker pull request #95
Opened 2022-04-24 16:04 UTC by juergenbr

**Motivation:**
My partner and I both use the app, and since we eat the same things most of the time we had to maintain the same database entries on every device we use separately. Another use case is moving to a new device, by exporting the database file and re-importing it the user does not have to re-create everything he added in the past.
This implementation allows to share either the complete database or only the product database with someone else.

**Implementation details:**
A new navigation menu entry titled "Database" with the corresponding new activity `activity_database.xml` was added. The activity contains two buttons, one to export the whole DB and one to only export products. Exporter and importer are separate classes, each using the respective DAOs to get the full dataset from/into the database. The ConsumedEntities and Products are returned as Lists inside an `ImpExModel.java` instance. Gson is used to transform that data into a json string, which is then stored as a .json file inside the apps internal storage (for a possible future "Restore" functionality) and handed over to an Intent to share the file with any other app accepting them (e.g. a messenger app, a cloud storage for archiving,..)
Import is also handled via a "View" intent. Opening the .json file will either open it directly with the Food Tracker intent handler activity or will show a selection of possible Apps able to handle .json files.

Privacy

2022-09-22 13:42 UTC, Kamuno commented
We had a major update with the Backup Integration which caused some merge conflicts. Can you have a look?

2022-09-22 13:43 UTC, Kamuno requested changes
Changes to due Backup Integration

2022-09-23 19:41 UTC, juergenbr commented
@Kamuno sure, I'll look into it

2022-09-24 10:35 UTC, juergenbr commented
@Kamuno it seems like the the project now requires that the developer has the backup-api source available on the local machine. I see that the Git Repo for the backup-api produces a zipped release, but does not publish into a repository.
Shouldn't this be decoupled so that the foodtracker project just references a specific version of the backup-api via gradle dependencies? Otherwise there is no way of knowing which source release was the used for developing the app.

2023-04-08 02:19 UTC, jaredandrews commented
@juergenbr did you ever update this branch to be mergeable? Considering doing it myself because I just got a new phone and am extremely frustrated that I cannot import data from my old device. Figured I should check. Thanks!

2023-04-08 11:54 UTC, juergenbr commented
@jaredandrews I just had another look. There have been a lot of changes since I opened the original PR. Since there is now a backup API available, merging my PR is more effort than implementing a backup based on the latest master. So I will close this PR.

2023-04-08 11:54 UTC, closed without merging